### PR TITLE
add dynamo db cache bundle to readme

### PR DESCRIPTION
**Pull request by RikudouSage**
We talked on Reddit with @mnapoli and he said that I should add the bundle into the Readme, so I'm doing that.

Let me know if that's OK and what I can improve.

### CODE REVIEW

**Comment by mnapoli** [comment]
Thank you!

That looks good, but I'd rather not have the details of the instructions in that page: if they change in the bundle that means that this documentation will not be up to date. So maybe it's better to add a paragraph and link to direct users to the bundle, and leave them to read the README of the bundle?

**Comment by RikudouSage** [comment]
That's why I included only the basic example, these options are the core so they're staying forever, I thought it would be better to have at least some example of usage. What do you think?

**Comment by mnapoli** [comment]
Unfortunately I've learned from experience that things eventually change. Let's keep it a link. Could you add it at the end of the page, after this section:

CleanShot 2020-09-28 at 10 28 03

**Comment by mnapoli** [comment]
Thanks!

**Pull request merged**
