### PR TITLE
bump PHP versions

### PR DESCRIPTION
**Pull request by chapeupreto**

### CODE REVIEW

**Comment by mnapoli** [comment]
Thanks, TBH I don't really want to rebuild layers every week (it's a very very long and manual process). Yes this could be automated, but it's a long work to automate that.

Do we need the absolute latest versions every time? I'm perfectly fine to update when there are significant fixes, but most of the time this brings no benefit to anyone.

**Comment by Nyholm** [comment]
I've automated things a bit in https://github.com/brefphp/extra-php-extensions/blob/master/.github/workflows/blackfire.yml

Could be nice to look at if one is starting with the automation

**Comment by mnapoli** [comment]
Yep that should be automated some day 😅

**Comment by andremohrmann** [comment]
This would be much appreciated since we are required to run the latest PHP version asap due to internal security guidelines.

**Comment by mnapoli** [comment]
@andremohrmann I can invite you to get in touch privately at matthieu@null.tc, I can provide support for such requirements via [Bref Enterprise](https://bref.sh/#enterprise).

**Comment by mnapoli** [comment]
Closing, I'm working on Bref 1.0 right now and I'm upgrading things there.

Thanks!

**Pull request closed without merging**
