### PR TITLE
Bumped PHP versions

### PR DESCRIPTION
**Pull request by GrahamCampbell**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Hmmm, CI not happy. 😭

**Comment by t-richard** [comment]
FYI the scheduled CI failed for the same reason yesterday https://github.com/brefphp/bref/actions/runs/1175994741

**Comment by mnapoli** [comment]
Right, this isn't related to this PR.

I've opened https://github.com/shivammathur/setup-php/issues/488, let's see if it's sorted out shortly.

**Comment by mnapoli** [comment]
Fixed, thanks for the new versions!

**Pull request merged**
