### PR TITLE
Update message Attributes

### PR DESCRIPTION
**Pull request by Nyholm**
I just want to make sure it is correct. 

Related to https://github.com/brefphp/symfony-messenger/pull/28

### CODE REVIEW

**Comment by mnapoli** [comment]
Thanks, I think the test that uses this needs to be updated because the build is now failing.

Also, are you sure about that change? Here is an example of a SQS event from the AWS docs: https://docs.aws.amazon.com/lambda/latest/dg/with-sqs.html Attributes do not look like what you changed.

**Comment by Nyholm** [comment]
Yes. Im sure. 

Note that there is a difference between `messageAttributes` and `attributes`. The link you sent is not showing any `messageAttributes`. 

I'll fix the test.

**Comment by mnapoli** [comment]
Yes of course! That's perfect thanks!

**Comment by Nyholm** [comment]
Thank you for merging.

**Pull request merged**
