### PR TITLE
Fixed the DomainName for s3-website

### PR DESCRIPTION
**Pull request by Chtiadrien**
Hello,

I copy/pasted the documentation for my latest project and when I deployed it, I got an S3 error from Cloudfront. After further inspection, I found the problem in the DomainName. 

S3 website domain name are written like that: `{bucket_name}.s3-website.eu-west-3.amazonaws.com`. In the documentation, it was like that: `{bucket_name}.s3-website-eu-west-3.amazonaws.com`

Hope it helps.

Edit: I've also fixed the error from PrettyCI 😉

### CODE REVIEW

**Comment by mnapoli** [comment]
Thanks! The thing is that the URL format depends on the region, see https://docs.aws.amazon.com/AmazonS3/latest/dev/WebsiteEndpoints.html

So it may be a `.` or a `-` 😕 (which is not great for user experience)

Maybe we could update the comment to link to this documentation page instead?

**Comment by Chtiadrien** [comment]
TIL

I've only worked in the eu-west-3 region, I didn't know this. 
I'll update the doc with a link to a nice table I found in the AWS documentation 😉 

Thanks!

**Comment by Chtiadrien** [comment]
I've been doing for research to simplify the configuration for the end user. I've end up with this:

```yaml
DomainName: !Select [2, !Split ["/", !GetAtt Assets.WebsiteURL]]
```

The WebsiteUrl attributes return the following: `http://mystack-mybucket-kdwwxmddtr2g.s3-website-us-east-2.amazonaws.com`. I then use Split and Select functions to extract the domain name.

If this is OK with you, I'll commit my changes.

**Comment by mnapoli** [comment]
Oh that's clever! Yes let's do that, thank you!

**Comment by mnapoli** [comment]
Thanks!

**Pull request merged**
