### PR TITLE
Document S3 assets deployment for Symfony

### PR DESCRIPTION
**Pull request by t-richard**
This PR is following some discussion we had on Slack regarding the improvement of the Symfony section of Bref docs.

This is mostly pasted from the same part of the [Laravel section](https://bref.sh/docs/frameworks/laravel.html#assets), adapted for Symfony and Webpack Encore.

### CODE REVIEW

**Comment by t-richard** [comment]
Marked it as draft so that I can test the last code example about Webpack Encore config. Not using Encore this way so I'm unsure if that piece of config is correct for what we do here.

I looked at https://symfony.com/doc/current/frontend/encore/cdn.html but it's unclear to me what config we must have to generate a manifest saying

```
"build/dashboard.js": "https://<bucket-name>.s3.amazonaws.com/build/dashboard.js"
```

**Review by mnapoli — COMMENTED** [review]
This is AWESOME!

I'll let you test that to make sure that it works, but it's absolutely perfect! Thank you!

**Comment by mnapoli** [comment]
> but it's unclear to me what config we must have to generate a manifest saying

Oh sorry about that part I haven't used Encore + S3 so I'm not really sure.

**Comment by t-richard** [comment]
Me neither, that's why I'll have to test this out 🙂

**Comment by t-richard** [comment]
Ok, the config was wrong :sweat_smile: 

I've updated the code sample.

This is now generating a manifest with lines like 
```
"build/app.js": "https://test-encore.s3.amazonaws.com/build/app.7da5d4f5.js"
```

Which is what we want because we deploy the whole public folder.

There's an example of this in the Encore's code comments https://github.com/symfony/webpack-encore/blob/main/index.js#L84

**Comment by mnapoli** [comment]
🚀  awesome thank you!

**Pull request merged**
