### PR TITLE
Use PHP 7.4.2

### PR DESCRIPTION
**Pull request by Nyholm**
PHP 7.4.2 will be released the 23rd of Januari. It contains some bugfixes that allow us to use preloading on an actual project. 

I am super excited to try it out. I've actually already started writing a blog post about it. Could we please merge this PR after PHP 7.4.2 is released so I can finish my blog post and brag about performance on Lambda?

### CODE REVIEW

**Comment by Nyholm** [comment]
I built a layer with RC1 here: arn:aws:lambda:eu-west-1:403367587399:layer:php-74RC1-fpm:1

**Comment by mnapoli** [comment]
Cool, looking forward to reading this!

> Could we please merge this PR after PHP 7.4.2 is released so I can finish my blog post and brag about performance on Lambda?

Let's wait for 7.4.2 then :)

**Comment by Nyholm** [comment]
Friendly ping

**Comment by mnapoli** [comment]
Oh yes we can merge that! Thanks!

**Pull request merged**
