### PR TITLE
Bump Version of AsyncAWS

### PR DESCRIPTION
**Pull request by swiffer**
Keep up with AsyncAWS until they are releasing 1.0

### CODE REVIEW

**Comment by mnapoli** [comment]
Thank you. Is there anything we need to change in the codebase? In notice the build is failing now.

**Comment by Nyholm** [comment]
The largest BC changes are: 
- We made many value objects final
- We moved classes used by both requests and responses to a separate namespace. (this is why PHPStan complains)

@swiffer I think the only change you need to do is to update a `use` statement. 

Sorry for all the updates. Currently (as always) I feel like there is no more BC breaks ahead of us.

**Comment by mnapoli** [comment]
@Nyholm thanks for the review! I have absolutely no problem with bc breaks by the way (since this is an internal lib).

**Comment by mnapoli** [comment]
Thank you!

**Pull request merged**
