### PR TITLE
There is a new PHP release in town!

### PR DESCRIPTION
**Pull request by afu-dev**
From 8.0.22 to 8.0.23 (security release).
From 8.1.9 to 8.1.10 (bug fix release).

I don't know if PHP 7.4 will be bumped (?).

### CODE REVIEW

**Comment by t-richard** [comment]
Could you please update 8.2 to beta3 too ?

**Comment by GrahamCampbell** [comment]
A PHP 7.4 release is not planned as far as I'm aware.

**Comment by GrahamCampbell** [comment]
It's available in https://downloads.php.net/~pierrick/ already, and the official homepage will be updated in the next few hours.

**Comment by t-richard** [comment]
Nice let's do RC1 then, thanks @GrahamCampbell !

**Comment by afu-dev** [comment]
RC1 pushed! Thanks for sharing @GrahamCampbell 🤗

**Review by GrahamCampbell — APPROVED** [review]

**Review by t-richard — APPROVED** [review]
Thanks!

**Pull request merged**
