### PR TITLE
#908 Support the new Serverless plugin variables introduced in 20210326

### LINKED ISSUE #908: Enabling variablesResolutionMode: 20210326
Adding the advised deprecation flag `variablesResolutionMode: 20210326` (NEW_VARIABLES_RESOLVER) results in the bref layer variable failing:

```yml
variablesResolutionMode: 20210326

functions:
  web:
    layers:
      - ${bref:layer.php-80-fpm}

plugins:
  - ./vendor/bref/bref
```

Output

```
Serverless Error ----------------------------------------
 
  Approached unrecognized configuration variable sources: "bref"

Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              14.16.0
     Framework Version:         2.33.1
     Plugin Version:            4.5.3
     SDK Version:               4.2.2
     Components Version:        3.8.1
```

### PR DESCRIPTION
**Pull request by mnapoli**
This fixes #908 

---

With:

```yaml
variablesResolutionMode: 20210326

functions:
  web:
    layers:
      - ${bref:layer.php-80-fpm}

plugins:
  - ./vendor/bref/bref
 ```

We get:

>   Approached unrecognized configuration variable sources: "bref"

Serverless has introduced a new way for plugins to declare custom variables. This PR adds support for that.

### CODE REVIEW

**Comment by yurwurk** [comment]
I wonder @mnapoli , did you tag this one ?

**Comment by sc0ttdav3y** [comment]
Looks like the current Bref release is still 1.2.3 which predates this merge. 

As of right now, we still cannot `variablesResolutionMode: 20210326` with Bref.

**Comment by mnapoli** [comment]
Yep yep, I started working on the release yesterday evening but couldn't finish it, I'll try to find the time today.

**Comment by sc0ttdav3y** [comment]
Excellent, I look forward to it.

**Comment by mnapoli** [comment]
I published [Bref 1.2.4](https://github.com/brefphp/bref/releases/tag/1.2.4)!

**Comment by sc0ttdav3y** [comment]
Thanks @mnapoli.  Should this also work for the extras repo? Or does something need to be done there too?

I'm still getting this:

```
Error: Unknown Bref variable ${bref:extra.redis-php-74},
```

My environment uses the following:

```
plugins:
  - ./vendor/bref/bref
  - ./vendor/bref/extra-php-extensions

functions:
  myFunction:
    layers:
      - ${bref:layer.php-74-fpm} # works
      - ${bref:extra.redis-php-74} # fails
```

Should I open another ticket over in that repo, or can you do your magic there too?

**Comment by sc0ttdav3y** [comment]
I just dived into your merged commit 🤦🏻 

```
                        throw new Error(`Unknown Bref variable \${bref:${address}}, the only supported syntax right now is \${bref:layer.XXX}`);
```

Lol, that's what I'm getting.

**Comment by sc0ttdav3y** [comment]
Actually, sorry but this is a blocker. I commented out `variablesResolutionMode: 20210326` but with 1.2.4 it still breaks pulling the extras layers with that exception.  

I'll pin to 1.2.3 for now, unless you tell me I should be doing something differently.

**Comment by mnapoli** [comment]
🤦  right the same needs to be done here: https://github.com/brefphp/extra-php-extensions/blob/master/index.js

I'll look into it right now, thanks for the update.

**Comment by mnapoli** [comment]
I've opened https://github.com/brefphp/extra-php-extensions/pull/219

**Comment by mnapoli** [comment]
@sc0ttdav3y can you test https://github.com/brefphp/extra-php-extensions/pull/219 and confirm whether it solves the problem?

**Comment by sc0ttdav3y** [comment]
@mnapoli Perhaps I'm missing something obvious, but it's still not working for me.

Here's `my composer.json` — using Bref 1.2.5 and the unmerged PR for Bref Extensions.

```
    "require": {
        "bref/bref": "^1.2.5",
        "bref/extra-php-extensions": "dev-fix-variable-resolution"
    }
```

My `serverless.yml` is the same as the initial post.

When I run `serverless deploy` I still get `Cannot resolve variable at "functions.test-php.layers.1": Error: Unknown Bref variable ${bref:extra.redis-php-74}, the only supported syntax right now is ${bref:layer.XXX}`

When I look at the latest release 1.2.5, it still fails at the same point because the `if` statement still only supports `bref:layer`, unchanged from 1.2.4:

```
if (!address.startsWith('layer.')) {
    throw new Error(`Unknown Bref variable \${bref:${address}}, the only supported syntax right now is \${bref:layer.XXX}`);
}
```
Reference: https://github.com/brefphp/bref/blob/master/index.js#L34

Doesn't it need to also support the `bref:extra` prefix?

Over at extra-php-extensions, I see the PR has `index.js` registering `bref-extra` as the config prefix.

At a whim, I tried updating my serverless.yml to this and see if a prefix change is what's expected:

```
    layers:
      - ${bref:layer.php-74-fpm}
      - ${bref-extra.redis-php-74} # <--- changed to bref-extra
```

When I deploy that, it gets past the exception thrown in bref, but I instead get another warning from Serverless:

```
Serverless: Configuration warning at 'functions['test-php'].layers[1]': unsupported configuration format
```

Down in CloudFormation in the update stack, I see `Layers` is broken as a result:

```
        "Layers": [
          "arn:aws:lambda:ap-southeast-2:209497400698:layer:php-74-fpm:18",
          "${bref-extra.redis-php-74}"
        ]
```

I guess there are a few problems and questions.

1. Firstly, I'm still blocked 😢 
2. Was there any other work in the bref project that didn't make it into 1.2.5 that's still on branch somewhere? Was I supposed to pull something other than 1.2.5?
3. Is the expectation that the `bref:extras` prefix will change to `bref-extras`? That was just a guess on my part.
4. Or have I just missed something obvious.

Thanks — happy to test again or help anyway I can.

**Comment by mnapoli** [comment]
@sc0ttdav3y thank you for testing!

Actually the change is more like this:

```yaml
    layers:
      - ${bref:layer.php-74-fpm}
      - ${bref-extra:redis-php-74}
```

Could you give it a try?

**Comment by sc0ttdav3y** [comment]
Yeah, I spotted that typo after posting. I actually tried but it didn’t work either. I’m away from my computer at present so I don’t have the exact error, but safe to say it failed.

**Comment by sc0ttdav3y** [comment]
@mnapoli I've re-tested using ` ${bref-extra:redis-php-74}` and it works. I'm happy to go with that if that's the future direction 🚀

**Comment by mnapoli** [comment]
Thanks for confirming, that's perfect, @Nyholm released a new version of bref-extra with that fix.

**Pull request merged**
