### PR TITLE
Upgrade Postgres to 14.2

### PR DESCRIPTION
**Pull request by HugoJF**
This seems to fix https://github.com/brefphp/bref/issues/965.

I have no clue what are the implications of this upgrade, but it seems to work fine for my use-case.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
This needs rebasing. :)

**Comment by mnapoli** [comment]
Before merging this it would be great if we knew what the impact was for upgrading the version by so much. I have no way of knowing if this is good or not.

**Comment by tillkruss** [comment]
I've love to see support for v14 instances.

**Comment by shadowhand** [comment]
Postgres is highly backwards compatible. As a Postgres user, I fully support this change.

**Comment by t-richard** [comment]
> Postgres is highly backwards compatible. 

This is my feeling too. 

This has been a recurring issue for a number of month now and may be blocking more users to use Bref with Postgres than it might cause harm.

Maybe we could merge this and tag a beta release. This would give the community actual layers to test it properly and give feedback ?

WDYT @mnapoli @deleugpn ?

**Comment by shadowhand** [comment]
@GrahamCampbell I agree with only making this change in PHP 8.x images.

**Comment by shadowhand** [comment]
To be clear: this is only upgrading the Postgres **client** which has (almost) nothing to do with the **server** or **database** version. 

The database version is always created with the current server version, so if my server is version 11.0 then my database will be created as version 11.0 and the database will need to be upgraded (see `pg_upgrade`) if the server is upgraded. However, the **client** protocol has not changed since version 7.4, so any version of the client will be able to communicate with any server >= 7.4.

Upgrading the client version is **very low risk** and, if anything, should improve functionality for any Postgres connection.

**Comment by allan-simon** [comment]
@mnapoli I've tested locally with version 9 to 14 of postgres on our application and I can confirm this PR works 

having it merged would allow us to upgrade in production our version of Postgresql , as the compatibility with bref is the only thing left

**Comment by allan-simon** [comment]
@mnapoli  thanks for the merge,  is it possible to have a version tagged :angel:  ?

**Comment by Nyholm** [comment]
Before we tag it, could someone with postgres < 12 confirm that this works? Or am I too afraid/careful?

**Comment by allan-simon** [comment]
> I've tested locally with version 9 to 14 of postgres on our application and I can confirm this PR works

already done :)

**Comment by mnapoli** [comment]
Thanks, I'll tag a release then.

**Comment by Nyholm** [comment]
Thank you @allan-simon <3

**Pull request merged**
