### PR TITLE
Tag docker images when tag on Github

### PR DESCRIPTION
**Pull request by Nyholm**
This PR make sure to tag and push docker images when we tag a release on Github. 

Before this is merged we need to update the "secure" environment variable in .travis.yaml. @mnapoli can you run the followng command and add the result to this PR? 

(From https://docs.travis-ci.com/user/encryption-keys/)

```
travis encrypt DOCKER_USERNAME=foo DOCKER_PASSWORD=bar -r brefphp/bref
```

I've tested this on my fork. See [the release](https://github.com/Nyholm/bref/releases/tag/47.11.13),  the [Travis job](https://travis-ci.org/Nyholm/bref/builds/627436966). It is only build on tags.

When I tested this I used a [different branch](https://github.com/Nyholm/bref/tree/tag-nyholm) on my fork because I wanted to test to build and push docker images.

### CODE REVIEW

**Comment by Nyholm** [comment]
This is related to #518

**Comment by mnapoli** [comment]
Thanks! You mentioned that builds take a long time (which isn't really surprising), but did it timeout? Or is it safe to merge?

**Comment by Nyholm** [comment]
The script is not timing out. But Travis cuts it after 50min so it cannot finish.

**Comment by mnapoli** [comment]
OK so as it is it's not ready to merge right?

I wonder if we could use Docker actions for this 🤔

**Comment by Nyholm** [comment]
I think this is working. Im just waiting for my github action to complete and make sure images are published on my Dockerhub. 

Github actions has a timelimit of 6 hours, compared to Travis 50 minutes. 

Notes: 
- This will only run on tags. Normal Travis CI is not affected. One could remove travis and add github actions for PRs too, but that is out of scope for this PR. 
- I separated `make docker-images` and `make publish-docker-images`. 
- I also separated the "base build" in `cd runtime ; make docker-images` to a separate target. I did that because it takes about 20 minutes to build the base docker image on Github action. This separation will make the build output a little bit prettier. 
- I also did some syntax changes. Instad of `cd runtime && make ...`, we do `cd runtime ; make ...`. As far as I know, the result is the same, but we use the latter on most places. So I changed to be consistent.

**Comment by Nyholm** [comment]
Hm.. The build was failing... https://github.com/Nyholm/bref/commit/381b282ab5a84c0e01797c879204a7757f97358f/checks?check_suite_id=395549328

```
 ---> Running in 73797d4f3f5a
+ mkdir -p /tmp/build/php
+ curl -Ls https://www.php.net/distributions/php-7.4.0.tar.gz
+ tar xzC /tmp/build/php --strip-components=1

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
The command '/bin/bash -c set -xe;     mkdir -p ${PHP_BUILD_DIR};     curl -Ls https://www.php.net/distributions/php-${VERSION_PHP}.tar.gz   | tar xzC ${PHP_BUILD_DIR} --strip-components=1' returned a non-zero code: 2
make[1]: *** [docker-images] Error 2
Makefile:30: recipe for target 'docker-images' failed
make: *** [docker-images] Error 2
make[1]: Leaving directory '/home/runner/work/bref/bref/runtime'
Makefile:9: recipe for target 'docker-images' failed
##[error]Process completed with exit code 2.
```

I'll try to revert my change with a separate "base image" layer.

**Comment by Nyholm** [comment]
Here is a "successful" build: https://github.com/Nyholm/bref/commit/f33929c496efe567c80ed3d6e773b5c2fa033100/checks?check_suite_id=395628903

It fails because of permissions to Docker. Luckily I cannot push to the official bref images. 

------

Here is another build that I just started. I replaced all docker's "bref/php*" references with my own namespace. It takes little more than an hour to build everything. Lets wait =)

https://github.com/Nyholm/bref/commit/2ee164d2adcef31bd58cbcb6c14405e96bb8fbba/checks?check_suite_id=395674294

Feel free to review the PR now.

**Comment by Nyholm** [comment]
Confirmed!

It is working =)

**Comment by mnapoli** [comment]
That's awesome! Thanks, I need to set the environment variables tomorrow and merge.

**Comment by Nyholm** [comment]
Yepp. 
You need to got to the settings for this repo, click on secrets and add: 

*  DOCKER_PASSWORD
* DOCKER_USERNAME

**Comment by mnapoli** [comment]
👍  I created an access token (which apparently can be used instead of the password)

**Comment by mnapoli** [comment]
I tagged a new release, it's building: https://github.com/brefphp/bref/runs/386366593

**Comment by Nyholm** [comment]
Thank you for merging.

**Pull request merged**
