### PR TITLE
Updated the README.md

### PR DESCRIPTION
**Pull request by andresayej**
to reflect the first known existence of all in one solution that simply works

### CODE REVIEW

**Comment by timoschaefer** [comment]
This reads more like an ad rather than outlining a fully-managed cloud solution - albeit a proprietary one that's tightly coupled to one framework - when we're about to get [documentation for even more frameworks](https://github.com/brefphp/bref/pull/419) which will get people to notice bref naturally, instead of being "hinted" in the direction of a competing, more limiting cloud solution.

Apart from requiring knowledge of either Cloudformation or Serverless configuration setups, bref is easy enough to setup, requiring only few lines of codes changed compared to "regular" deployments using e.g. Docker. Plus the current documentation is extensive and exhaustive enough to guide you through the migration every step of the way to get you started with PHP on Lambda within hours.

**Comment by andresayej** [comment]
So a better place for this would be in docs/frameworks/laravel.md?

**Comment by mnapoli** [comment]
We don't need to put that advertisement in the documentation. It just doesn't make sense to me (and it seems I'm not the only one).

> So a better place for this would be in docs/frameworks/laravel.md?

No 🤷‍♂

**Comment by andresayej** [comment]
@mnapoli 👍 
The pull request is closed, so that settles it i guess.

**Pull request closed without merging**
