### PR TITLE
Bumped PHP versions to latest patch version

### PR DESCRIPTION
**Pull request by peldax**
Raised PHP versions to latest patch version.

- 7.3.27
- 7.4.16
- 8.0.3

### CODE REVIEW

**Review by GrahamCampbell — APPROVED** [review]

**Comment by mnapoli** [comment]
Thank you, I'll build those releases.

**Comment by GrahamCampbell** [comment]
🎉 :shipit:

**Comment by mnapoli** [comment]
https://github.com/brefphp/bref/releases/tag/1.2.1 Thanks for the PR!

**Comment by shadowhand** [comment]
@mnapoli what about the layer versions? I am being impacted by https://github.com/laminas/laminas-code/issues/79 and it doesn't seem that the lambda layers for PHP 8 are updated to 8.0.3.

**Comment by shadowhand** [comment]
Never mind, we don't have latest bref and that's why we're still getting layer version "3".

**Pull request merged**
