### PR TITLE
Added all missing region

### PR DESCRIPTION
**Pull request by zxc20033**
Added all missing region

### CODE REVIEW

**Comment by Chtiadrien** [comment]
Maybe we should add all missing regions?

With `ap-east-1` added, we are only missing:

```
ap-northeast-3 (Asia Pacific - Osaka-Local)
cn-north-1 (China - Beijing)
cn-northwest-1 (China - Ningxia)
me-south-1 (Middle East - Bahrain)
```

**Comment by zxc20033** [comment]
> Maybe we should add all missing regions?
> 
> With `ap-east-1` added, we are only missing:
> 
> ```
> ap-northeast-3 (Asia Pacific - Osaka-Local)
> cn-north-1 (China - Beijing)
> cn-northwest-1 (China - Ningxia)
> me-south-1 (Middle East - Bahrain)
> ```

Yep, I have checked these regions are providing lambda. Updated the pull request to include all regions.

**Comment by Chtiadrien** [comment]
I've double check and I realize that the `ap-northeast-3 (Asia Pacific - Osaka-Local)` does not provide AWS Lambda 😕  Sorry about that.

image

The region will be standardized in the early 2021 : https://aws.amazon.com/about-aws/whats-new/2020/01/aws-to-launch-standard-aws-region-in-osaka-in-early-2021/

**Comment by zxc20033** [comment]
> I've double check and I realize that the `ap-northeast-3 (Asia Pacific - Osaka-Local)` does not provide AWS Lambda 😕 Sorry about that.
> 
> image
> 
> The region will be standardized in the early 2021 : https://aws.amazon.com/about-aws/whats-new/2020/01/aws-to-launch-standard-aws-region-in-osaka-in-early-2021/

weird, from this blog I saw there are lambda layers for ap-northeast-3 https://aws.amazon.com/tw/blogs/compute/upcoming-changes-to-the-python-sdk-in-aws-lambda/ 
image

**Comment by richardnbanks** [comment]
The CN regions cannot be added as a separate account is required for the Chinese region. https://github.com/brefphp/bref/issues/422#issuecomment-524598714

**Comment by mnapoli** [comment]
Thanks for the PR!

> The CN regions cannot be added as a separate account is required for the Chinese region. #422 (comment)

Until we have an easy way to deal with this, I will not publish layers on these regions unfortunately :/

Also, unless we are certain about `ap-northeast-3` I'd rater remove it from the list (building layers takes a lot of time, I'd rather avoid loosing time on this).

**Comment by mnapoli** [comment]
Closing because it seems this PR is stuck for now.

**Pull request closed without merging**
