### PR TITLE
Replace a bunch of http links with https

### PR DESCRIPTION
**Pull request by GrahamCampbell**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
@mnapoli 👋

**Comment by mnapoli** [comment]
Hey, I was looking at this but I actually don't really want to merge this 😬

I'm rewriting the whole docs in #1596, changing this on master will create unnecessary conflicts. I'd rather avoid this on master (changing this to target #1596 could work though)

**Comment by GrahamCampbell** [comment]
Can we merge just the two changes from `tests` for now?

**Comment by mnapoli** [comment]
Yes we can

**Comment by GrahamCampbell** [comment]
Done.

**Pull request merged**
