### PR TITLE
Function runtime: force restarting the process for failed invocations

### PR DESCRIPTION
**Pull request by mnapoli**
This is a continuation of #1013.

In the function runtime, the PHP process will now always be restarted if the invocation failed. That change only impacts apps that use `BREF_LOOP_MAX` to keep the process alive.

The reason for this is that, in most cases, a failed invocation means the PHP application threw an exception.

When using `BREF_LOOP_MAX`, the PHP process is kept alive, and it is important for the application to cleanup global state.

If an exception was thrown, it is likely the cleanup wasn't done, or wasn't done properly. It sounds much safer to restart the process.

The downside is a slight performance cost: around 10ms to restart the process. But that provides a safer execution environment.

### CODE REVIEW

**Review by shouze — APPROVED** [review]

**Review by GrahamCampbell — APPROVED** [review]

**Review by t-richard — APPROVED** [review]

**Comment by deleugpn** [comment]
As a rule of thumb, I don't like functions that have a boolean return as a way "silence" exceptions. More often than not it's more useful to move the try catch upwards so that not only you have the failure signal but also the ability to make different (non-binary) decisions based on information available on the exception.
On the other hand, since LambdaRuntime is an internal class, it's possible to make such a change at another point in time and disregard the BC break. This does look simpler than letting the exception bubble up specially in the limited use case.

**Review by deleugpn — APPROVED** [review]

**Comment by GrahamCampbell** [comment]
This is a significant enough change, that I think this warrants bumping to 1.3.0, giving people a little more control over upgrading.

**Comment by mnapoli** [comment]
👍  good point

**Comment by Nyholm** [comment]
Thank you for merging. I've followed up by https://github.com/php-runtime/runtime/pull/82

**Pull request merged**
