### PR TITLE
Removed extra space

### PR DESCRIPTION
**Pull request by Nyholm**
Follow up form #830

### CODE REVIEW

**Review by shouze — APPROVED** [review]
Ooops :angel: good catch! :pray:

**Review by shouze — APPROVED** [review]

**Comment by Nyholm** [comment]
Im just sorry I didnt catch it earlier

**Comment by mnapoli** [comment]
Hi! Are you both sure about that?

It looks like a correct way to disable the `entrypoint` right? The next argument is the Docker image, unless I'm mistaken.

**Comment by Nyholm** [comment]
Sorry, I wasnt aware that it was trying to disable the entyrpoint. It just looked like a syntax error. 

> Are you both sure about that?

No

**Comment by shouze** [comment]
> Hi! Are you both sure about that?
> 
> It looks like a correct way to disable the `entrypoint` right? The next argument is the Docker image, unless I'm mistaken.

Ho yes in fact it's ok. We can replace `--entrypoint=` by `---entrypoint=squash` as this docker option syntax is a bit weird sometimes.

**Review by shouze — CHANGES_REQUESTED** [review]
Sorry in fact it's fine... docker options syntax is weird sometimes

**Comment by mnapoli** [comment]
No worries, let's close this. TBH that looks good to me like that.

**Comment by Nyholm** [comment]
Thank you

**Pull request closed without merging**
