### PR TITLE
Added Imagick extension

### PR DESCRIPTION
**Pull request by victormacko**
Imagick offers some more advanced (and OO orientated) image manipulation features on top of what GD offers, so this extension was added to cater for more complex needs (above & beyond what GD allows). I've used it in a project already on Lambda and works a treat!

GD is awesome to have, especially as quite a few of the PHP libraries (eg. PDF generation, and phpoffice (spreadsheets) required it).
Admittedly i've used Imagick on one project thus far, and wanted to 'pay it forward' for others to use too :)

Ref for anyone wanting to take a look; https://www.php.net/manual/en/book.imagick.php

The nitty gritty;
For anyone wanting to use this prior to it being merged in - just clone this branch, and;
1) run 'composer install' to get things going
2) goto the 'runtimes' dir in your command line (eg. run 'cd runtimes')
3) run 'make layers'
4) once it's finished, there'll be a bunch of zip files in the 'runtimes/export' dir -- these are your lambda layers.
5) run the following to upload the layers to your AWS account so you can use them with lambda .. changing the 'region' to whatever region you need to use;
aws lambda publish-layer-version --region=ap-southeast-2 --layer-name=php-73-fpm-with-imagick --zip-file fileb://php-73-fpm.zip --compatible-runtimes provided --output text
aws lambda publish-layer-version --region=ap-southeast-2 --layer-name=php-73-with-imagick --zip-file fileb://php-73.zip --compatible-runtimes provided --output text

6) find the ARN of your two new layers (either from the output, or in your AWS console in the lambda page), and specify it in your serverless.yaml / cloudformation template.
7) enable it on the php.ini file in your lambda function

The file sizes before inclusion are;
$ ls -al
-rw-r--r--   1 victor  staff       746 11 Sep 14:08 console.zip
-rw-r--r--   1 victor  staff  35479457 11 Sep 14:19 php-72-fpm.zip
-rw-r--r--   1 victor  staff  25936316 11 Sep 14:19 php-72.zip
-rw-r--r--   1 victor  staff  35649154 11 Sep 14:19 php-73-fpm.zip
-rw-r--r--   1 victor  staff  25991753 11 Sep 14:19 php-73.zip

File sizes after inclusion of the extension;
-rw-r--r--   1 victor  staff       746 11 Sep 14:08 console.zip
-rw-r--r--   1 victor  staff  35871702 12 Sep 00:30 php-72-fpm.zip
-rw-r--r--   1 victor  staff  26328563 12 Sep 00:29 php-72.zip
-rw-r--r--   1 victor  staff  36143950 12 Sep 00:30 php-73-fpm.zip
-rw-r--r--   1 victor  staff  26486547 12 Sep 00:29 php-73.zip

totals;

php-72-fpm.zip is 392,245 bytes larger = 1.1055552513 % increase
php-72.zip is 392,247 bytes larger = 1.51234663 % increase
php-73-fpm.zip is 494,796 bytes larger = 1.38796001 % increase
php-73.zip is 494,794 bytes larger = 1.90365767 % increase

Average increase of 1.477 % across the 4 zip files (443520 bytes / 433kb).

Hope it helps!

### CODE REVIEW

**Comment by mnapoli** [comment]
Thank you for sharing this. That looks good, especially since it only adds to the layer roughly the same thing as GD.

Let's leave this open for at least a few days to see what others think about this.

**Comment by AlessandroMinoccheri** [comment]
I think that it's a very common library in some projects so I think that could be very useful for many developers

**Comment by viezel** [comment]
@mnapoli whats stopped us from merging it?

**Comment by mnapoli** [comment]
I need to check out the size unzipped, and test it.

**Comment by JGamboa** [comment]
thank you @victormacko

**Comment by JGamboa** [comment]
@victormacko could you help me to learn about this? i need to add the xsl extension

**Comment by victormacko** [comment]
> @victormacko could you help me to learn about this? i need to add the xsl extension

I can try ... best way to start is to clone the master repo, then edit the 'runtime/php-intermediary.Dockerfile' file to include your extension ... compile it using the instructions I included above, and give it a try!

**Comment by JGamboa** [comment]
@victormacko 
searching on the internet i found this 
RUN apt-get install -y libxslt-dev
RUN docker-php-ext-install xsl

that should be put on the dockerfile?

**Comment by victormacko** [comment]
The first line yes, I think the other line you'll need to do in a similar way the other extensions are included ... the changes need to be made in "php-intermediary.Dockerfile".
If you're stuck, best approach is to jump onto the slack channel for Bref.

**Comment by mnapoli** [comment]
Thank you!

**Pull request merged**
